sudo: required
language: python
services:
  - memcached
python:
- '2.7'
- '3.4'
- pypy
install: 
- "pip install -r requirements.txt"
- "pip install -r requirements-dev.txt"
# command to run tests
script: tox
