version: "2"

services:
  memcached:
    restart: on-failure:10
    image: memcached:latest
    command: memcached -m 1000
    ports: 
      - "11211:11211"
  web:
    restart: on-failure:10
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - memcached

