version: "2"

services:
  memcached:
    restart: on-failure:10
    image: memcached:latest
    command: memcached -m 1000
    ports: 
      - "11211:11211"
  web:
    restart: on-failure:10
    build: .
    command: gunicorn zapier.wsgi:application -b :8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - memcached

