# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20160716_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 16, 15, 56, 34, 883181, tzinfo=utc)),
        ),
    ]
