# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20160716_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'payfast', b'PayFast')], max_length=30)),
                ('fields', models.TextField(default=b'[]')),
            ],
        ),
        migrations.CreateModel(
            name='GatewayProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=255)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Charity')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Gateway')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[(b'pending', b'Pending'), (b'active', b'Active'), (b'complete', b'Complete'), (b'cancelled', b'Cancelled')], default=b'pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 16, 16, 2, 13, 809746, tzinfo=utc)),
        ),
    ]
