# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20160716_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GatewayProperties',
            new_name='GatewayProperty',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 16, 16, 10, 43, 798783, tzinfo=utc)),
        ),
    ]
