# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 16:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20160716_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='fields',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 16, 16, 24, 0, 253647, tzinfo=utc)),
        ),
    ]
