# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20160716_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='gateway',
            field=models.ManyToManyField(through='campaign.GatewayProperty', to='campaign.Gateway'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gatewayproperty',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
