# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20160716_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='gatewayproperty',
            name='gateway',
        ),
        migrations.AddField(
            model_name='gatewayproperty',
            name='gateway_name',
            field=models.CharField(choices=[(b'payfast', b'PayFast')], default=b'payfast', max_length=30),
        ),
        migrations.DeleteModel(
            name='Gateway',
        ),
    ]
