# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20160716_1645'),
        ('campaign', '0003_auto_20160716_1556'),
    ]

    operations = [
    ]
