# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20160716_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[(b'started', b'Started'), (b'complete', b'Complete')], default=b'started', max_length=30),
        ),
    ]
