# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 17, 14, 10, 41, 17239, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='expiry_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 17, 14, 10, 43, 750924, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
