# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_auto_20160717_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
