# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_remove_campaign_raised'),
        ('campaign', '0008_merge'),
    ]

    operations = [
    ]
