# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
